### ISSUE TITLE
Sort By Best Rated

### ISSUE THREAD

**Issue by Simon-Laux** [jkelol111/webstore#14]
**Is your feature request related to a problem? Please describe.**
There are options for sorting, but the "sort by rating option" is missing:
![2021-05-09_17-07](https://user-images.githubusercontent.com/18725968/117577242-4d8eba00-b0e9-11eb-8ee8-17176fe1be83.png)
(I assume popularity means download-count)

**Describe the solution you'd like**
Introduction of a selection item, that lets me sort the app by rating.

**Comment by jkelol111** [comment]
Sorting by rating isn't really feasible as of now because there's no way to get a full list of ratings of all apps in one call from the ratings server (retrieving ratings for each app individually when the db is reloaded is slow), and some apps may not have any ratings, so I'm leaving this issue here to implement once those issues are rectified.

**Comment by Simon-Laux** [comment]
also showing ratings on the overview would be nice.

**Comment by Simon-Laux** [comment]
created an issue for it on the rating server repo: https://gitlab.com/banana-hackers/simple-ratings-server/-/issues/6
